[versions]

gson = "2.13.2"
jdkVersion = "21"
koog = "0.5.3"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1-0.6.x-compat"
ktlint = "1.8.0"
ktor = "3.3.3"
slf4j = "2.0.17"
testcontainers = "1.21.3"

[libraries]

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
koog-agents-core = { module = "ai.koog:agents-core", version.ref = "koog" }
koog-prompt-executor-llms-all = { module = "ai.koog:prompt-executor-llms-all", version.ref = "koog" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
testcontainers-ollama = { module = "org.testcontainers:ollama", version.ref = "testcontainers" }

[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
