name: self-hosted

on:
  workflow_dispatch:  # Manual trigger

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:

      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      # - run: ./gradlew ciJobsMatrixSetup --stacktrace

      - id: set_matrix
        run: echo "matrix=$(jq -c . < ./matrix_self_hosted.json)" >> $GITHUB_OUTPUT



  Koog:
    needs: prepare_matrix
    runs-on: ${{ matrix.variants.runs-on }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare_matrix.outputs.matrix) }}
    name: ${{ matrix.variants.artifact-name }} ${{ matrix.variants.ollama-model-id }} ${{ matrix.variants.runs-on }}
    steps:

      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew clean :ollama:test -Dollama-model-id=${{ matrix.variants.ollama-model-id }} --tests "${{ matrix.variants.test-group }}" --stacktrace
        if: ${{ matrix.variants.enabled }}

      - name: Sanitize ollama-model-id
        if: always()
        run: echo "SANITIZED_OLLAMA_MODEL_ID=$(echo '${{ matrix.variants.ollama-model-id }}' | tr ',:/' '-')" >> $GITHUB_ENV

      - name: Collect reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: reports-${{ env.SANITIZED_OLLAMA_MODEL_ID }}-${{ matrix.variants.artifact-name }}-${{ matrix.variants.runs-on }}
          path: |
            **/build/reports/
          retention-days: 7
